sudo: required

language: generic

services:
    - docker

before_install:
    - echo "start Creating an image with dockerfile"
    - docker build -t chopokmado/react_dev -f Dockerfile.dev .

script:
    - docker run -e CI=true chopokmado/react_dev npm run test -- --coverage

after_success:
    - echo "Test Success"